project_id = "gjubbtbrkvjcucesaqmq"

[functions.send-whatsapp]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.create-pix]
verify_jwt = false

[functions.check-pix-status]
verify_jwt = false

[functions.notify-order]
verify_jwt = false